apiVersion: batch/v1
kind: Job
metadata:
  name: presync-verify-sbom
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: verify-sbom
          image: ghcr.io/sigstore/cosign/cosign:v2.2.4
          args:
            - "verify-attestation"
            - "--type"
            - "spdx"
            - "--certificate-oidc-issuer"
            - "https://token.actions.githubusercontent.com"
            - "--certificate-identity-regexp"
            - "https://github.com/sudhmca/appRepo/.*"
            - "__IMAGE_REF__"
          env:
            - name: COSIGN_EXPERIMENTAL
              value: "true"